# Uncomment the next line to define a global platform for your project
# platform :ios, '11.4'

target 'swift4.2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'SocketRocket'

  # Pods for swift4.2

end
